### ISSUE TITLE
cert-operator needs retry logic if creating the cert fails

### ISSUE THREAD

**Issue by rossf7** [giantswarm/cert-operator#10]
Ideally should use exponential backoff retry logic from microkit.

**Comment by rossf7** [comment]
Wrong repo

**Comment by asymmetric** [comment]
@rossf7 what failures should we try to recover from?

**Comment by rossf7** [comment]
Sorry late reply on this.

I think we should retry if we get errors connecting to the Vault API. As well as when creating or deleting secrets.

- [ ] PKI setup https://github.com/giantswarm/cert-operator/blob/master/service/ca/pki.go#L14
- [ ] Issue cert https://github.com/giantswarm/cert-operator/blob/master/service/crt/cert_signer.go#L15
- [ ] Create secret https://github.com/giantswarm/cert-operator/blob/master/service/crt/k8s_secret.go#L13
- [ ] Delete secret https://github.com/giantswarm/cert-operator/blob/master/service/crt/k8s_secret.go#L43
