### ISSUE TITLE
Missing/nonpublic certctl repo

### ISSUE THREAD

**Issue by kopiczko** [giantswarm/cert-operator#26]
Code of github.com/giantswarm/certctl is checked in to the vendor directory, but it's unavailable in a separate github repo (https://github.com/giantswarm/certctl responds with 404).

**Comment by rossf7** [comment]
Yes certctl is currently private and I have a task to make it public. Thanks for the reminder :) I'll get this fixed.

**Comment by rossf7** [comment]
Certctl is now public.
