### ISSUE TITLE
CA logic in cert-operator should move to a CA operator with its own TPR

### ISSUE THREAD

**Issue by rossf7** [giantswarm/cert-operator#27]
Currently the cert-operator handles CA setup and issuing certs. This should be split out to a CA operator with its own TPR. The TPR should contain the default TTL for the CA which is currently a constant.

**Comment by rossf7** [comment]
As well as splitting the CA logic into a separate operator we also need to remove the PKI backend creation logic from cluster-service. Currently it creates the PKI backend during cluster setup before kubernetesd creates the certs TPOs.

The CA TPO will need to contain the set of allowed domains for all certificates. See giantswarm/aws-operator#142 we need to include 127.0.0.1 in this list for the etcd cert.

**Comment by xh3b4sd** [comment]
I am not sure on this anymore. IMO we should migrate to the reconciler framework and implement a dedicated CA resource. This should be a good enough separation. I am just proactive now and close this issue. Feel free to reopen when we want to have more discussions on this.
