### ISSUE TITLE
label certificates with their cluster id

### ISSUE THREAD

**Issue by JosephSalisbury** [giantswarm/cert-operator#33]
I'd like to be able to do:

```
kubectl get certificates -l=cluster=foobar
```
to grab all the certificates belonging to one cluster (grepping makes me sad)

**Comment by rossf7** [comment]
Yes we label the generated secrets but not the certificate TPOs. We'd need to do this in kubernetesd. Also creating the TPOs in the cluster namespace would help and is on the backlog.

https://github.com/giantswarm/kubernetesd/issues/82

**Comment by rossf7** [comment]
This was done
