### ISSUE TITLE
Need to check certificatetpr exists before starting the watch

### ISSUE THREAD

**Issue by rossf7** [giantswarm/cert-operator#44]
Error below can happen if the watch starts before the TPR has been created.

```
{"caller":"github.com/giantswarm/cert-operator/service/crt/service.go:131","info":"starting watch","time":"17-05-16 08:16:03.222"}
E0516 08:16:03.224005       1 reflector.go:199] github.com/giantswarm/cert-operator/vendor/k8s.io/client-go/tools/cache/reflector.go:94: Failed to list *certificatetpr.CustomObject: the server could not find the requested resource
```

We should check the TPR exists and this should be fixed in `operatorkit` as it applies to all operators.

**Comment by kopiczko** [comment]
There's a ready code in operatorkit, still need to be used in cert-operator.

**Comment by kopiczko** [comment]
Fixed by https://github.com/giantswarm/cert-operator/pull/53
Tested locally.
