### ISSUE TITLE
Not enough permissions in Vault for new healthz check

### ISSUE THREAD

**Issue by r7vme** [giantswarm/cert-operator#65]
I think this change https://github.com/giantswarm/cert-operator/pull/63 breaks kvm install for me 

I can be wrong, but let me describe what i'm getting.

I have cert-operator configured with token that we're generating [here](https://github.com/giantswarm/hive/blob/master/playbooks/vault_generic_secrets.yml#L28-L38)

And cert-oprator and I getting permission denied for `/v1/sys/mounts` path, but with token i can issue new cert (see below)?

```
[rs@tpad tmp]$ export VAULT_TOKEN=XXXXXXXXX
[rs@tpad tmp]$ export VAULT_ADDR=http://172.16.238.2:8200
[rs@tpad tmp]$ curl -H "X-Vault-Token: $VAULT_TOKEN" http://172.16.238.2:8200/v1/sys/mounts
{"errors":["permission denied"]}
[rs@tpad tmp]$ echo '{"ttl": "3460h", "common_name": "foobarcert.g8s.local"}' | vault write pki-g8s/issue/role-g8s -
Key                     Value
---                     -----
certificate             -----BEGIN CERTIFICATE-----
MIIDVTCCAj2gAwIBAgIUPhOQo21jqD12mbKVZs0/NndIXt8wDQYJKoZIhvcNAQEL

```

**Comment by rossf7** [comment]
I think this is a different issue. `cert-operator` is working on AWS but not sure on KVM. Is the `cert-operator` pod healthy?

This change was to add a `/healthz` endpoint for the liveness and readiness probes. I needed an API call that would check the Vault token but without affecting Vault. So I chose listing the sysmounts.

A Vault health API was added in `0.7.3` and I'd rather use that. But we need to upgrade the Vault servers first.

https://github.com/hashicorp/vault/blob/master/CHANGELOG.md#073-june-7th-2017

WDYT?

**Comment by r7vme** [comment]
@rossf7 thanks for explanation, @JosephSalisbury pointed that i need additional policies in Vault https://github.com/giantswarm/giantswarm/wiki/AWS-Cluster-Vault-Setup that i don't have currently

**Comment by r7vme** [comment]
I'll check and if it the case i'll close the issue

**Comment by r7vme** [comment]
Yes the problem that i need to add more permissions. Closing as this should be covered in secrets management track not in cert-opertor.
